/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.proyecto_final_p1.ui;

import com.mycompany.proyecto_final_p1.model.Cobros;
import com.mycompany.proyecto_final_p1.model.Pago;
import com.mycompany.proyecto_final_p1.util.CobrosDAO;
import com.mycompany.proyecto_final_p1.util.PagoDAO;
import java.sql.SQLException;
import java.util.Calendar;
import java.util.List;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author cinto
 */
public class ConsultaPagos extends javax.swing.JFrame {
    private List<Cobros> listaCobros;
    private CobrosDAO cobrosDAO = new CobrosDAO();
    private PagoDAO pagoDAO = new PagoDAO();
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ConsultaPagos.class.getName());

    /**
     * Creates new form ConsultaPagos
     */
    public ConsultaPagos() {
        initComponents();
        cargarCobros();
    }
    
    private void cargarCobros() {
        try {
            jComboBox1.removeAllItems();
            listaCobros = cobrosDAO.listarCobros();
            for (Cobros c : listaCobros) {
                Calendar cal = Calendar.getInstance();
                cal.setTime(c.getFechaInicio());
                int mes = cal.get(Calendar.MONTH) + 1;
                int anio = cal.get(Calendar.YEAR);
                jComboBox1.addItem(getNombreMes(mes) + " " + anio);
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        btnDescargarPDF = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        lblTotalEsperado = new javax.swing.JLabel();
        lblTotalRecaudado = new javax.swing.JLabel();
        lblDiferencia = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 51, 102));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jButton1.setText("CONSULTAR");
        jButton1.addActionListener(this::jButton1ActionPerformed);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel3.setText("MES PARA CONSULTAR:");

        jLabel1.setFont(new java.awt.Font("Comic Sans MS", 0, 36)); // NOI18N
        jLabel1.setText("REPORTE GENERAL");

        jButton2.setBackground(new java.awt.Color(204, 0, 0));
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("REGRESAR AL MENÚ");

        btnDescargarPDF.setText("DESCARGAR");
        btnDescargarPDF.addActionListener(this::btnDescargarPDFActionPerformed);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/descargas.png"))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, 164, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel1))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(81, 81, 81)
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel3)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(88, 88, 88))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnDescargarPDF)
                        .addGap(36, 36, 36))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 73, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(btnDescargarPDF)
                                .addComponent(jButton2)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(15, 15, 15))
        );

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        lblTotalEsperado.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setText("RESUMEN");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(lblTotalEsperado, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(144, 144, 144)
                .addComponent(lblTotalRecaudado)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblDiferencia)
                .addGap(156, 156, 156))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jLabel2)
                .addGap(2, 2, 2)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTotalEsperado, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTotalRecaudado)
                    .addComponent(lblDiferencia))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 395, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            int indice = jComboBox1.getSelectedIndex();
            if (indice == -1) {
                return;
            }
            int idCobro = listaCobros.get(indice).getIdCobro();

            DefaultTableModel modelo = new DefaultTableModel(
                    new String[]{"No. Casa", "Propietario", "Estado", "Total Pagado Año"}, 0
            );

            List<Pago> pagos = pagoDAO.listarPagosPorCobro(idCobro);
            int totalEsperado = 0;
            int totalRecaudado = 0;
            int anio = Calendar.getInstance().get(Calendar.YEAR);

            for (Pago p : pagos) {
                totalEsperado += p.getMontoPagado();
                if (p.isPagado()) totalRecaudado += p.getMontoPagado();

                int totalAnio = pagoDAO.totalPagadoAnioPorCasa(p.getIdCasa(), anio);

                modelo.addRow(new Object[]{
                    p.getNumeroCasa(),
                    p.getNombrePropietario(),
                    p.isPagado() ? "Pagado" : "Pendiente",
                    "Q." + totalAnio
                });
            }

            jTable1.setModel(modelo);
            lblTotalEsperado.setText("Total esperado: Q." + totalEsperado);
            lblTotalRecaudado.setText("Total recaudado: Q." + totalRecaudado);
            lblDiferencia.setText("Diferencia: Q." + (totalEsperado - totalRecaudado));

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnDescargarPDFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDescargarPDFActionPerformed
        if (listaCobros == null || jComboBox1.getSelectedIndex() == -1) {
            JOptionPane.showMessageDialog(this, "Por favor, consulte primero.");
            return;
        }

        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setDialogTitle("Guardar Reporte General");
        fileChooser.setSelectedFile(new java.io.File("Reporte_General_" + jComboBox1.getSelectedItem().toString().replace(" ", "_") + ".pdf"));
        int seleccion = fileChooser.showSaveDialog(this);

        if (seleccion == JFileChooser.APPROVE_OPTION) {
            java.io.File archivo = fileChooser.getSelectedFile();
            String ruta = archivo.getAbsolutePath();
            if (!ruta.toLowerCase().endsWith(".pdf")) {
                ruta += ".pdf";
            }

            com.lowagie.text.Document documento = new com.lowagie.text.Document();
            try {
                com.lowagie.text.pdf.PdfWriter.getInstance(documento, new java.io.FileOutputStream(ruta));
                documento.open();

                // Fuentes
                com.lowagie.text.Font fuenteTitulo = new com.lowagie.text.Font(
                        com.lowagie.text.Font.HELVETICA, 20, com.lowagie.text.Font.BOLD,
                        new java.awt.Color(0, 51, 102));
                com.lowagie.text.Font fuenteSubtitulo = new com.lowagie.text.Font(
                        com.lowagie.text.Font.HELVETICA, 12, com.lowagie.text.Font.BOLD,
                        new java.awt.Color(0, 51, 102));
                com.lowagie.text.Font fuenteNormal = new com.lowagie.text.Font(
                        com.lowagie.text.Font.HELVETICA, 10);
                com.lowagie.text.Font fuenteBlanca = new com.lowagie.text.Font(
                        com.lowagie.text.Font.HELVETICA, 10, com.lowagie.text.Font.BOLD,
                        java.awt.Color.WHITE);

                // Título
                com.lowagie.text.Paragraph titulo = new com.lowagie.text.Paragraph(
                        "REPORTE GENERAL DE PAGOS", fuenteTitulo);
                titulo.setAlignment(com.lowagie.text.Element.ALIGN_CENTER);
                documento.add(titulo);

                // Línea separadora
                com.lowagie.text.Paragraph linea = new com.lowagie.text.Paragraph(
                        "________________________________________________",
                        new com.lowagie.text.Font(com.lowagie.text.Font.HELVETICA, 10,
                                com.lowagie.text.Font.NORMAL, new java.awt.Color(0, 51, 102)));
                linea.setAlignment(com.lowagie.text.Element.ALIGN_CENTER);
                documento.add(linea);
                documento.add(new com.lowagie.text.Paragraph(" "));

                // Mes consultado
                documento.add(new com.lowagie.text.Paragraph(
                        "Mes consultado: " + jComboBox1.getSelectedItem().toString(), fuenteSubtitulo));
                documento.add(new com.lowagie.text.Paragraph(
                        "Fecha de Emisión: " + java.time.LocalDate.now(), fuenteNormal));
                documento.add(new com.lowagie.text.Paragraph(" "));

                // Tabla
                com.lowagie.text.pdf.PdfPTable tablaPDF = new com.lowagie.text.pdf.PdfPTable(4);
                tablaPDF.setWidthPercentage(100);

                // Encabezados
                String[] columnas = {"No. Casa", "Propietario", "Estado", "Total Pagado Año"};
                for (String col : columnas) {
                    com.lowagie.text.pdf.PdfPCell celda = new com.lowagie.text.pdf.PdfPCell(
                            new com.lowagie.text.Phrase(col, fuenteBlanca));
                    celda.setBackgroundColor(new java.awt.Color(0, 51, 102));
                    celda.setHorizontalAlignment(com.lowagie.text.Element.ALIGN_CENTER);
                    celda.setPadding(8);
                    tablaPDF.addCell(celda);
                }

                // Filas
                int filasTabla = jTable1.getRowCount();
                for (int i = 0; i < filasTabla; i++) {
                    for (int j = 0; j < 4; j++) {
                        com.lowagie.text.pdf.PdfPCell celda = new com.lowagie.text.pdf.PdfPCell(
                                new com.lowagie.text.Phrase(
                                        jTable1.getValueAt(i, j).toString(), fuenteNormal));
                        if (i % 2 == 0) {
                            celda.setBackgroundColor(new java.awt.Color(235, 241, 255));
                        }
                        // Colorear estado
                        if (j == 2) {
                            String estado = jTable1.getValueAt(i, j).toString();
                            if (estado.equals("Pendiente")) {
                                celda.setBackgroundColor(new java.awt.Color(255, 220, 220));
                            } else {
                                celda.setBackgroundColor(new java.awt.Color(220, 255, 220));
                            }
                        }
                        celda.setPadding(6);
                        celda.setHorizontalAlignment(com.lowagie.text.Element.ALIGN_CENTER);
                        tablaPDF.addCell(celda);
                    }
                }
                documento.add(tablaPDF);
                documento.add(new com.lowagie.text.Paragraph(" "));

                // Resumen
                documento.add(new com.lowagie.text.Paragraph("RESUMEN DEL MES", fuenteSubtitulo));
                documento.add(new com.lowagie.text.Paragraph(
                        lblTotalEsperado.getText(), fuenteNormal));
                documento.add(new com.lowagie.text.Paragraph(
                        lblTotalRecaudado.getText(), fuenteNormal));
                documento.add(new com.lowagie.text.Paragraph(
                        lblDiferencia.getText(), fuenteNormal));

                JOptionPane.showMessageDialog(this, "¡PDF generado y guardado con éxito!");

            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Error al generar el PDF: " + e.getMessage(),
                        "Error", JOptionPane.ERROR_MESSAGE);
            } finally {
                if (documento.isOpen()) {
                    documento.close();
                }
            }
        }
    }//GEN-LAST:event_btnDescargarPDFActionPerformed
    
    private String getNombreMes(int mes) {
        String[] meses = {"Enero", "Febrero", "Marzo", "Abril", "Mayo", "Junio",
                          "Julio", "Agosto", "Septiembre", "Octubre", "Noviembre", "Diciembre"};
        return meses[mes - 1];
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new ConsultaPagos().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDescargarPDF;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lblDiferencia;
    private javax.swing.JLabel lblTotalEsperado;
    private javax.swing.JLabel lblTotalRecaudado;
    // End of variables declaration//GEN-END:variables
}

