/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.proyecto_final_p1.ui;

import com.mycompany.proyecto_final_p1.model.Casa;
import com.mycompany.proyecto_final_p1.util.CasaDAO;
import com.mycompany.proyecto_final_p1.util.CuotaDAO;
import java.util.List;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author gabri
 */
public class EstadoCuentaView extends javax.swing.JFrame {
    private CasaDAO casaDAO = new CasaDAO();
    private CuotaDAO cuotaDAO = new CuotaDAO();
    private List<Casa> listaCasas;

    /**
     * Creates new form EstadoCuentaView
     */
    public EstadoCuentaView() {
        initComponents();
        this.setLocationRelativeTo(null); // Centra la pantalla
        cargarCasasComboBox(); // Llena el combo con la BD
    }
private void cargarCasasComboBox() {
        try {
            jComboBoxCasas.removeAllItems();
            listaCasas = casaDAO.listarCasas();
            
            for (Casa c : listaCasas) {
                jComboBoxCasas.addItem("Casa No. " + c.getNumeroCasa());
            }
            
            if (!listaCasas.isEmpty()) {
                cargarEstadoCuentaTabla(listaCasas.get(0).getIdCasa());
            }
            
        } catch (java.sql.SQLException e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Error al cargar las casas: " + e.getMessage());
        }
    }

    private void cargarEstadoCuentaTabla(int idCasa) {
        String[] columnas = {"Año", "Mes", "Monto Cuota", "Monto Pagado", "Estado"};
        javax.swing.table.DefaultTableModel modelo = new javax.swing.table.DefaultTableModel(columnas, 0);
        
        try {
            java.util.List<String[]> datos = cuotaDAO.obtenerEstadoCuentaPorCasa(idCasa);
            for (String[] fila : datos) {
                modelo.addRow(fila);
            }
            jTableEstadoCuenta.setModel(modelo);
        } catch (java.sql.SQLException e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Error al llenar la tabla: " + e.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableEstadoCuenta = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnDescargarPDF = new javax.swing.JButton();
        jComboBoxCasas = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 51, 102));

        jTableEstadoCuenta.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTableEstadoCuenta);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/estado-cuenta-vista.png"))); // NOI18N

        btnDescargarPDF.setText("DESCARGAR");
        btnDescargarPDF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDescargarPDFActionPerformed(evt);
            }
        });

        jComboBoxCasas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBoxCasas.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBoxCasasItemStateChanged(evt);
            }
        });
        jComboBoxCasas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxCasasActionPerformed(evt);
            }
        });

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/descargas.png"))); // NOI18N

        jButton1.setBackground(new java.awt.Color(204, 0, 0));
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("REGRESAR AL MENÚ");
        jButton1.setToolTipText("");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnDescargarPDF)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 197, Short.MAX_VALUE)
                .addComponent(jComboBoxCasas, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(62, 62, 62))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(185, 185, 185))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnDescargarPDF)
                        .addComponent(jComboBoxCasas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel2))
                .addGap(19, 19, 19))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(16, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBoxCasasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxCasasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxCasasActionPerformed

    private void jComboBoxCasasItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBoxCasasItemStateChanged
        // TODO add your handling code here:
        if (evt.getStateChange() == java.awt.event.ItemEvent.SELECTED) {
            int indice = jComboBoxCasas.getSelectedIndex();
            if (indice != -1 && listaCasas != null) {
                Casa casaSeleccionada = listaCasas.get(indice);
                cargarEstadoCuentaTabla(casaSeleccionada.getIdCasa());
            }
        }
    }//GEN-LAST:event_jComboBoxCasasItemStateChanged

    private void btnDescargarPDFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDescargarPDFActionPerformed
        int indice = jComboBoxCasas.getSelectedIndex();
        if (indice == -1) {
            JOptionPane.showMessageDialog(this, "Por favor, seleccione una casa primero.");
            return;
        }
        Casa casaSeleccionada = listaCasas.get(indice);
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setDialogTitle("Guardar Estado de Cuenta");
        fileChooser.setSelectedFile(new java.io.File("Estado_Cuenta_Casa_" + casaSeleccionada.getNumeroCasa() + ".pdf"));
        int seleccion = fileChooser.showSaveDialog(this);
        if (seleccion == JFileChooser.APPROVE_OPTION) {
            java.io.File archivoGuardar = fileChooser.getSelectedFile();
            String ruta = archivoGuardar.getAbsolutePath();
            if (!ruta.toLowerCase().endsWith(".pdf")) {
                ruta += ".pdf";
            }

            com.lowagie.text.Document documento = new com.lowagie.text.Document();
            try {
                com.lowagie.text.pdf.PdfWriter.getInstance(documento, new java.io.FileOutputStream(ruta));
                documento.open();

                // Fuentes
                com.lowagie.text.Font fuenteTitulo = new com.lowagie.text.Font(
                        com.lowagie.text.Font.HELVETICA, 20, com.lowagie.text.Font.BOLD,
                        new java.awt.Color(0, 51, 102));
                com.lowagie.text.Font fuenteSubtitulo = new com.lowagie.text.Font(
                        com.lowagie.text.Font.HELVETICA, 12, com.lowagie.text.Font.BOLD,
                        new java.awt.Color(0, 51, 102));
                com.lowagie.text.Font fuenteNormal = new com.lowagie.text.Font(
                        com.lowagie.text.Font.HELVETICA, 10);
                com.lowagie.text.Font fuenteBlanca = new com.lowagie.text.Font(
                        com.lowagie.text.Font.HELVETICA, 10, com.lowagie.text.Font.BOLD,
                        java.awt.Color.WHITE);

                // Título
                com.lowagie.text.Paragraph titulo = new com.lowagie.text.Paragraph(
                        "ESTADO DE CUENTA DE CONDOMINIO", fuenteTitulo);
                titulo.setAlignment(com.lowagie.text.Element.ALIGN_CENTER);
                documento.add(titulo);

                // Línea separadora
                com.lowagie.text.Paragraph linea = new com.lowagie.text.Paragraph(
                        "________________________________________________",
                        new com.lowagie.text.Font(com.lowagie.text.Font.HELVETICA, 10,
                                com.lowagie.text.Font.NORMAL, new java.awt.Color(0, 51, 102)));
                linea.setAlignment(com.lowagie.text.Element.ALIGN_CENTER);
                documento.add(linea);
                documento.add(new com.lowagie.text.Paragraph(" "));

                // Info de la casa
                documento.add(new com.lowagie.text.Paragraph(
                        "Número de Casa: " + casaSeleccionada.getNumeroCasa(), fuenteSubtitulo));
                documento.add(new com.lowagie.text.Paragraph(
                        "Fecha de Emisión: " + java.time.LocalDate.now(), fuenteNormal));
                documento.add(new com.lowagie.text.Paragraph(" "));

                // Tabla
                com.lowagie.text.pdf.PdfPTable tablaPDF = new com.lowagie.text.pdf.PdfPTable(5);
                tablaPDF.setWidthPercentage(100);

                // Encabezados con fondo azul
                String[] columnas = {"Año", "Mes", "Monto Cuota", "Monto Pagado", "Estado"};
                for (String col : columnas) {
                    com.lowagie.text.pdf.PdfPCell celda = new com.lowagie.text.pdf.PdfPCell(
                            new com.lowagie.text.Phrase(col, fuenteBlanca));
                    celda.setBackgroundColor(new java.awt.Color(0, 51, 102));
                    celda.setHorizontalAlignment(com.lowagie.text.Element.ALIGN_CENTER);
                    celda.setPadding(8);
                    tablaPDF.addCell(celda);
                }

                // Filas con color alternado
                int filasTabla = jTableEstadoCuenta.getRowCount();
                int totalEsperado = 0;
                int totalPagado = 0;

                for (int i = 0; i < filasTabla; i++) {
                    for (int j = 0; j < 5; j++) {
                        com.lowagie.text.pdf.PdfPCell celda = new com.lowagie.text.pdf.PdfPCell(
                                new com.lowagie.text.Phrase(
                                        jTableEstadoCuenta.getValueAt(i, j).toString(), fuenteNormal));
                        if (i % 2 == 0) {
                            celda.setBackgroundColor(new java.awt.Color(235, 241, 255));
                        }
                        // Colorear estado
                        if (j == 4) {
                            String estado = jTableEstadoCuenta.getValueAt(i, j).toString();
                            if (estado.equals("Pendiente")) {
                                celda.setBackgroundColor(new java.awt.Color(255, 220, 220));
                            } else {
                                celda.setBackgroundColor(new java.awt.Color(220, 255, 220));
                            }
                        }
                        celda.setPadding(6);
                        celda.setHorizontalAlignment(com.lowagie.text.Element.ALIGN_CENTER);
                        tablaPDF.addCell(celda);
                    }
                    // Acumular totales
                    try {
                        String montoCuota = jTableEstadoCuenta.getValueAt(i, 2).toString().trim().replace("Q.", "");
                        String montoPagado = jTableEstadoCuenta.getValueAt(i, 3).toString().trim().replace("Q.", "");

                        if (!montoCuota.isEmpty()) {
                            totalEsperado += Integer.parseInt(montoCuota);
                        }
                        if (!montoPagado.isEmpty()) {
                            totalPagado += Integer.parseInt(montoPagado);
                        }
                    } catch (NumberFormatException e) {
                        System.out.println("Error parseando: " + e.getMessage());
                    }
                }
                documento.add(tablaPDF);
                documento.add(new com.lowagie.text.Paragraph(" "));

                // Resumen de totales
                documento.add(new com.lowagie.text.Paragraph("RESUMEN", fuenteSubtitulo));
                documento.add(new com.lowagie.text.Paragraph(
                        "Total esperado: Q" + totalEsperado, fuenteNormal));
                documento.add(new com.lowagie.text.Paragraph(
                        "Total pagado: Q" + totalPagado, fuenteNormal));
                documento.add(new com.lowagie.text.Paragraph(
                        "Diferencia: Q" + (totalEsperado - totalPagado), fuenteNormal));

                JOptionPane.showMessageDialog(this, "¡PDF generado y guardado con éxito!");

            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Error al generar el PDF: " + e.getMessage(),
                        "Error", JOptionPane.ERROR_MESSAGE);
            } finally {
                if (documento.isOpen()) {
                    documento.close();
                }
            }
        }
    }//GEN-LAST:event_btnDescargarPDFActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Menu ventana = new Menu();
        ventana.setLocationRelativeTo(this);
        ventana.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EstadoCuentaView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EstadoCuentaView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EstadoCuentaView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EstadoCuentaView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EstadoCuentaView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDescargarPDF;
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBoxCasas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableEstadoCuenta;
    // End of variables declaration//GEN-END:variables
}
