/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.proyecto_final_p1.ui;

import javax.swing.JOptionPane;

/**
 *
 * @author umg
 */
public class Menu extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Menu.class.getName());

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
        // Maximiza la ventana en ambos sentidos (Horizontal y Vertical)
    this.setExtendedState(javax.swing.JFrame.MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu_Archivo = new javax.swing.JMenu();
        jMenu_Reinicio_Clave = new javax.swing.JMenuItem();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        jMenu_Salir1 = new javax.swing.JMenuItem();
        jMenu_Opciones = new javax.swing.JMenu();
        jMenu_Manto_Propietario = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMenu_Manto_Casa = new javax.swing.JMenuItem();
        jMenu_Finanzas = new javax.swing.JMenu();
        jMenu_Registro_Pagos = new javax.swing.JMenuItem();
        jSeparator4 = new javax.swing.JPopupMenu.Separator();
        jMenu_Control_Cobros = new javax.swing.JMenuItem();
        jMenu_Reportes = new javax.swing.JMenu();
        jMenu_Casas_Morosas = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Menu Principal");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jMenu_Archivo.setText("Archivo");

        jMenu_Reinicio_Clave.setText("Rinicio de Clave");
        jMenu_Reinicio_Clave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu_Reinicio_ClaveActionPerformed(evt);
            }
        });
        jMenu_Archivo.add(jMenu_Reinicio_Clave);
        jMenu_Archivo.add(jSeparator3);

        jMenu_Salir1.setText("Salir");
        jMenu_Salir1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu_Salir1ActionPerformed(evt);
            }
        });
        jMenu_Archivo.add(jMenu_Salir1);

        jMenuBar1.add(jMenu_Archivo);

        jMenu_Opciones.setText("Administración");

        jMenu_Manto_Propietario.setText("Propietario");
        jMenu_Manto_Propietario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu_Manto_PropietarioActionPerformed(evt);
            }
        });
        jMenu_Opciones.add(jMenu_Manto_Propietario);
        jMenu_Opciones.add(jSeparator1);

        jMenu_Manto_Casa.setText("Casa");
        jMenu_Manto_Casa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu_Manto_CasaActionPerformed(evt);
            }
        });
        jMenu_Opciones.add(jMenu_Manto_Casa);

        jMenuBar1.add(jMenu_Opciones);

        jMenu_Finanzas.setText("Finanzas");

        jMenu_Registro_Pagos.setText("Registro de Pagos");
        jMenu_Registro_Pagos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu_Registro_PagosActionPerformed(evt);
            }
        });
        jMenu_Finanzas.add(jMenu_Registro_Pagos);
        jMenu_Finanzas.add(jSeparator4);

        jMenu_Control_Cobros.setText("Control de Cobros");
        jMenu_Control_Cobros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu_Control_CobrosActionPerformed(evt);
            }
        });
        jMenu_Finanzas.add(jMenu_Control_Cobros);

        jMenuBar1.add(jMenu_Finanzas);

        jMenu_Reportes.setText("Reportes");

        jMenu_Casas_Morosas.setText("Casas Morosas");
        jMenu_Casas_Morosas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu_Casas_MorosasActionPerformed(evt);
            }
        });
        jMenu_Reportes.add(jMenu_Casas_Morosas);

        jMenuBar1.add(jMenu_Reportes);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(209, 209, 209)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(247, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(125, 125, 125)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(152, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenu_Manto_PropietarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu_Manto_PropietarioActionPerformed
        // 1. Creamos el objeto de la ventana. 
    // 'this' significa que este Menú es el dueño del diálogo.
    // 'true' significa que es modal (bloquea el menú hasta cerrar).
    PropietarioView ventanaMantoPropietario = new PropietarioView();
    
    // 2. Centrar la ventanita respecto al menú
    ventanaMantoPropietario.setLocationRelativeTo(this);
    
    // 3. Hacerla visible
    ventanaMantoPropietario.setVisible(true);
    }//GEN-LAST:event_jMenu_Manto_PropietarioActionPerformed

    private void jMenu_Manto_CasaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu_Manto_CasaActionPerformed
        // Creamos el objeto de la ventana
    // 'this' es el JFrame (Menu), 'true' la hace modal
    CasaView ventana = new CasaView();
    
    // La centramos respecto al menú
    ventana.setLocationRelativeTo(this);
    
    // La hacemos aparecer
    ventana.setVisible(true);
    }//GEN-LAST:event_jMenu_Manto_CasaActionPerformed

    private void jMenu_Reinicio_ClaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu_Reinicio_ClaveActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenu_Reinicio_ClaveActionPerformed

    private void jMenu_Salir1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu_Salir1ActionPerformed
        // 1. Mostrar el cuadro de diálogo de confirmación
    int respuesta = JOptionPane.showConfirmDialog(
            this, 
            "¿Está seguro de que desea cerrar sesión?", 
            "Confirmar Salida", 
            JOptionPane.YES_NO_OPTION, 
            JOptionPane.QUESTION_MESSAGE
    );
    
    // 2. Si la respuesta es SÍ (YES_OPTION)
    if (respuesta == JOptionPane.YES_OPTION) {
        
        // Creamos la ventana de Login
        LoginView ventanaLogin = new LoginView();
        
        // La hacemos visible y la centramos
        ventanaLogin.setVisible(true);
        ventanaLogin.setLocationRelativeTo(null);
        
        // Cerramos el menú actual para liberar memoria
        this.dispose();
    }
    }//GEN-LAST:event_jMenu_Salir1ActionPerformed

    private void jMenu_Registro_PagosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu_Registro_PagosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenu_Registro_PagosActionPerformed

    private void jMenu_Control_CobrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu_Control_CobrosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenu_Control_CobrosActionPerformed

    private void jMenu_Casas_MorosasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu_Casas_MorosasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenu_Casas_MorosasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Menu().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenu_Archivo;
    private javax.swing.JMenuItem jMenu_Casas_Morosas;
    private javax.swing.JMenuItem jMenu_Control_Cobros;
    private javax.swing.JMenu jMenu_Finanzas;
    private javax.swing.JMenuItem jMenu_Manto_Casa;
    private javax.swing.JMenuItem jMenu_Manto_Propietario;
    private javax.swing.JMenu jMenu_Opciones;
    private javax.swing.JMenuItem jMenu_Registro_Pagos;
    private javax.swing.JMenuItem jMenu_Reinicio_Clave;
    private javax.swing.JMenu jMenu_Reportes;
    private javax.swing.JMenuItem jMenu_Salir1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    private javax.swing.JPopupMenu.Separator jSeparator4;
    // End of variables declaration//GEN-END:variables
}
