/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.proyecto_final_p1.ui;
import com.mycompany.proyecto_final_p1.util.PropietarioDAO;

/**
 *
 * @author Admin
 */
public class PropietarioView extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(PropietarioView.class.getName());

    /**
     * Creates new form PropietarioView
     */
    public PropietarioView() {
        initComponents();
        refrescarTabla();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelPropietario = new javax.swing.JPanel();
        scpPropietarios = new javax.swing.JScrollPane();
        tblPropietarios = new javax.swing.JTable();
        jPanelEncabezado = new javax.swing.JPanel();
        btnAnadir = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        lblGestionPropietario = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanelPropietario.setBackground(new java.awt.Color(0, 51, 102));

        tblPropietarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "Nombre", "Telefono", "Correo"
            }
        ));
        scpPropietarios.setViewportView(tblPropietarios);

        jPanelEncabezado.setBackground(new java.awt.Color(255, 255, 255));

        btnAnadir.setText("AÑADIR");
        btnAnadir.addActionListener(this::btnAnadirActionPerformed);

        btnModificar.setText("MODIFICAR");
        btnModificar.addActionListener(this::btnModificarActionPerformed);

        btnEliminar.setText("INACTIVAR");
        btnEliminar.addActionListener(this::btnEliminarActionPerformed);

        btnSalir.setBackground(new java.awt.Color(204, 0, 0));
        btnSalir.setForeground(new java.awt.Color(255, 255, 255));
        btnSalir.setText("SALIR AL MENÚ");
        btnSalir.addActionListener(this::btnSalirActionPerformed);

        lblGestionPropietario.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblGestionPropietario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Propietarios.png"))); // NOI18N

        javax.swing.GroupLayout jPanelEncabezadoLayout = new javax.swing.GroupLayout(jPanelEncabezado);
        jPanelEncabezado.setLayout(jPanelEncabezadoLayout);
        jPanelEncabezadoLayout.setHorizontalGroup(
            jPanelEncabezadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelEncabezadoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnSalir)
                .addGap(104, 104, 104)
                .addComponent(btnAnadir, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addGroup(jPanelEncabezadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelEncabezadoLayout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(lblGestionPropietario))
                    .addGroup(jPanelEncabezadoLayout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(btnModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(216, Short.MAX_VALUE))
        );
        jPanelEncabezadoLayout.setVerticalGroup(
            jPanelEncabezadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelEncabezadoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanelEncabezadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblGestionPropietario)
                    .addComponent(btnSalir))
                .addGap(21, 21, 21)
                .addGroup(jPanelEncabezadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnModificar)
                    .addComponent(btnAnadir)
                    .addComponent(btnEliminar))
                .addGap(52, 52, 52))
        );

        lblGestionPropietario.getAccessibleContext().setAccessibleName("");

        javax.swing.GroupLayout jPanelPropietarioLayout = new javax.swing.GroupLayout(jPanelPropietario);
        jPanelPropietario.setLayout(jPanelPropietarioLayout);
        jPanelPropietarioLayout.setHorizontalGroup(
            jPanelPropietarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPropietarioLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(scpPropietarios)
                .addContainerGap())
            .addGroup(jPanelPropietarioLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jPanelEncabezado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );
        jPanelPropietarioLayout.setVerticalGroup(
            jPanelPropietarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPropietarioLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jPanelEncabezado, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(scpPropietarios, javax.swing.GroupLayout.PREFERRED_SIZE, 377, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelPropietario, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelPropietario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAnadirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnadirActionPerformed
        // TODO add your handling code here:
        // Apertura ventana para agregar propietario
        // 'this' es la ventana actual, y 'true' la hace modal (bloquea la de atrás)
        PropietarioFormDialog dialog = new PropietarioFormDialog(new javax.swing.JFrame(), true);
        dialog.setLocationRelativeTo(this); // Para que salga centrada
        dialog.setVisible(true); // La mostramos
        refrescarTabla();
    }//GEN-LAST:event_btnAnadirActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        Menu ventana = new Menu();
        ventana.setLocationRelativeTo(this);
        ventana.setVisible(true);
        this.dispose(); // Esto cierra solo el cuadrito de registro y libera la memoria.
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
// 1. Obtener la fila que el usuario tiene seleccionada en la JTable
    int filaSeleccionada = tblPropietarios.getSelectedRow();
    
    // 2. Validar que realmente haya seleccionado una fila
    if (filaSeleccionada == -1) {
        javax.swing.JOptionPane.showMessageDialog(this, 
                "Por favor, seleccione un propietario de la tabla para poder modificarlo.", 
                "Fila no seleccionada", 
                javax.swing.JOptionPane.WARNING_MESSAGE);
        return; // Detiene la ejecución del botón
    }
    
    // 3. Extraer el ID de la fila seleccionada (Columna 0)
    int idPropietario = (int) tblPropietarios.getValueAt(filaSeleccionada, 0);
    
    // 4. Abrir el formulario enviándole el ID (UNA SOLA VEZ)
    PropietarioFormDialog ventanaEditar = new PropietarioFormDialog(this, true, idPropietario);
    ventanaEditar.setLocationRelativeTo(this); // Centrar la ventanita
    ventanaEditar.setVisible(true); // Mostrar la ventana
    
    // 5. Línea de refrescar comentada para evitar el error anterior
    //cargarDatosTabla();
     refrescarTabla();
    }//GEN-LAST:event_btnModificarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEliminarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new PropietarioView().setVisible(true));
    }

        // Creamos una instancia global o local del DAO en la vista
    private PropietarioDAO dao = new PropietarioDAO();

    public void refrescarTabla() {
        // 1. Llamamos al DAO para traer la lista actualizada de la base de datos
        java.util.List<com.mycompany.proyecto_final_p1.model.Propietario> lista = dao.listarTodos();

        // 2. Obtenemos el modelo de tu JTable (reemplaza 'tblPropietarios' por el nombre exacto de tu tabla)
        javax.swing.table.DefaultTableModel modelo = (javax.swing.table.DefaultTableModel) tblPropietarios.getModel();

        // 3. Limpiamos la tabla para que no se dupliquen los datos al recargar
        modelo.setRowCount(0);

        // 4. Recorremos la lista de propietarios usando un ciclo for-each
        for (com.mycompany.proyecto_final_p1.model.Propietario p : lista) {

            // Creamos la fila ordenando los datos según tus columnas: [ID, Nombre, Telefono, Correo]
            Object[] fila = new Object[4];
            fila[0] = p.getIdPropietario();
            fila[1] = p.getNombre();
            fila[2] = p.getTelefono();
            fila[3] = p.getCorreo();

            // 5. Agregamos la fila al modelo de la tabla
            modelo.addRow(fila);
        }
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAnadir;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnModificar;
    private javax.swing.JButton btnSalir;
    private javax.swing.JPanel jPanelEncabezado;
    private javax.swing.JPanel jPanelPropietario;
    private javax.swing.JLabel lblGestionPropietario;
    private javax.swing.JScrollPane scpPropietarios;
    private javax.swing.JTable tblPropietarios;
    // End of variables declaration//GEN-END:variables
}
