/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package com.mycompany.proyecto_final_p1.ui;

/**
 *
 * @author cinto
 */
public class PropietarioFormDialog extends javax.swing.JDialog {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(PropietarioFormDialog.class.getName());
    
    // 1. Variable global de control única
    private int idPropietarioModificar = -1; 
    
    /**
     * CONSTRUCTOR ORIGINAL (Para nuevos registros)
     */
    public PropietarioFormDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    // ==========================================
    // >>> Nuevo constructor para actualizar propietario <<<
    // ==========================================
    public PropietarioFormDialog(java.awt.Frame parent, boolean modal, int idPropietario) {
        super(parent, modal);
        initComponents();
        this.idPropietarioModificar = idPropietario;
        
        // Cambiar títulos visuales
        lblTitulo.setText("Modificar Propietario");
        btnGuardar.setText("Actualizar");
        
        // Cargar los datos actuales en los campos de texto
        cargarDatosParaModificar();
    }

    private void cargarDatosParaModificar() {
        com.mycompany.proyecto_final_p1.util.PropietarioDAO dao = new com.mycompany.proyecto_final_p1.util.PropietarioDAO();
        com.mycompany.proyecto_final_p1.model.Propietario p = dao.buscarPorId(this.idPropietarioModificar);
        
        if (p != null) {
            txtNombre.setText(p.getNombre());
            txtTelefono.setText(p.getTelefono());
            txtCorreo.setText(p.getCorreo());
        }
    }
    // ==========================================
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();
        lblNombre = new javax.swing.JLabel();
        lblTelefono = new javax.swing.JLabel();
        lblCorreo = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        txtTelefono = new javax.swing.JTextField();
        txtCorreo = new javax.swing.JTextField();
        btnGuardar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 0, 51));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        lblTitulo.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitulo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Ingresar-Propietario (2).png"))); // NOI18N

        lblNombre.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblNombre.setText("NOMBRE:");

        lblTelefono.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblTelefono.setText("TELÉFONO:");

        lblCorreo.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblCorreo.setText("CORREO:");

        txtNombre.setToolTipText("Ingrese su nombre completo");
        txtNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNombreKeyTyped(evt);
            }
        });

        txtTelefono.setToolTipText("Ingresar el numero de telefono en formato + [CodPaís] [Espacio en Blanco] [Número]");

        txtCorreo.setToolTipText("Su correo debe contener \"@\" y \".com\"");

        btnGuardar.setText("GUARDAR");
        btnGuardar.addActionListener(this::btnGuardarActionPerformed);

        btnCancelar.setBackground(new java.awt.Color(204, 0, 0));
        btnCancelar.setForeground(new java.awt.Color(255, 255, 255));
        btnCancelar.setText("CANCELAR");
        btnCancelar.addActionListener(this::btnCancelarActionPerformed);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(btnGuardar)
                        .addGap(18, 18, 18)
                        .addComponent(btnCancelar))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(82, 82, 82)
                        .addComponent(lblTitulo)))
                .addGap(80, 80, 80)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(lblTelefono, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtCorreo)
                            .addComponent(txtTelefono)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(lblNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(37, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(28, Short.MAX_VALUE)
                .addComponent(lblTitulo)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGuardar)
                    .addComponent(btnCancelar))
                .addGap(15, 15, 15))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNombre))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTelefono)
                    .addComponent(txtTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCorreo)
                    .addComponent(txtCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(26, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        // TODO add your handling code here:
        this.dispose(); // Esto cierra solo el cuadrito de registro y libera la memoria.
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
// 1. Recolectar los datos y forzar MAYÚSCULAS en el nombre usando .toUpperCase()
    String nombre = txtNombre.getText().trim().toUpperCase();
    String telefono = txtTelefono.getText().trim();
    String correo = txtCorreo.getText().trim();

    // Actualizamos el cuadro de texto visualmente para que el usuario vea que se cambió a mayúsculas
    txtNombre.setText(nombre);

    // 2. Validar que no dejen campos vacíos
    if (nombre.isEmpty() || telefono.isEmpty() || correo.isEmpty()) {
        javax.swing.JOptionPane.showMessageDialog(this, 
                "Por favor, llene todos los campos obligatorios.", 
                "Error de validación", 
                javax.swing.JOptionPane.WARNING_MESSAGE);
        return; 
    }

    // 2.1 VALIDACIÓN DE CORREO
    String regexCorreo = "^[\\w.-]+@[\\w.-]+\\.[a-zA-Z]{2,}$";
    if (!correo.matches(regexCorreo)) {
        javax.swing.JOptionPane.showMessageDialog(this, 
                "El formato del correo electrónico no es válido.\nDebe incluir '@' y un dominio (ejemplo: usuario@correo.com).", 
                "Formato Incorrecto", 
                javax.swing.JOptionPane.ERROR_MESSAGE);
        return; 
    }

    // 2.2 VALIDACIÓN DE TELÉFONO
    String regexTelefono = "^\\+\\d{1,3}\\s\\d{4,11}$";
    if (!telefono.matches(regexTelefono)) {
        javax.swing.JOptionPane.showMessageDialog(this, 
                "El teléfono debe cumplir con el formato internacional simplificado:\n" +
                "+[CódigoPaís] [Espacio en Blanco] [NúmeroCompleto]\n" +
                "Ejemplo válido: +502 45678901", 
                "Formato Incorrecto", 
                javax.swing.JOptionPane.ERROR_MESSAGE);
        return; 
    }

    // =======================================================================
    // >>> PASO C REESTRUCTURADO (PUNTOS 3 Y 4 UNIFICADOS) <<<
    // =======================================================================
    
    // 3. Crear el objeto Propietario con los datos ya limpios y validados
    com.mycompany.proyecto_final_p1.model.Propietario propietario = 
            new com.mycompany.proyecto_final_p1.model.Propietario(nombre, telefono, correo, 1);

    // 4. Instanciar el DAO y decidir mediante IF si se inserta o se actualiza
    com.mycompany.proyecto_final_p1.util.PropietarioDAO dao = 
            new com.mycompany.proyecto_final_p1.util.PropietarioDAO();
    
    boolean exito;

    if (this.idPropietarioModificar == -1) {
        // Modo Registro: El ID se mantiene en -1 por defecto, es un registro nuevo
        exito = dao.insertar(propietario);
    } else {
        // Modo Edición: Le inyectamos el ID que seleccionamos de la tabla antes de mandar al DAO
        propietario.setIdPropietario(this.idPropietarioModificar); 
        exito = dao.actualizar(propietario); // Ejecuta la sentencia UPDATE en la BD
    }
    
    // =======================================================================

    // 5. Avisar al usuario del resultado (Funciona perfectamente para ambos casos)
    if (exito) {
        javax.swing.JOptionPane.showMessageDialog(this, 
                "Propietario guardado exitosamente.", 
                "Éxito", 
                javax.swing.JOptionPane.INFORMATION_MESSAGE);
        this.dispose(); 
    } else {
        javax.swing.JOptionPane.showMessageDialog(this, 
                "No se pudo guardar el propietario. Revise los datos o la conexión.", 
                "Error", 
                javax.swing.JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void txtNombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNombreKeyTyped
        // 1. Obtener el carácter físico que el usuario acaba de presionar
    char caracter = evt.getKeyChar();
    
    // 2. Verificar si el carácter es una letra minúscula
    if (Character.isLowerCase(caracter)) {
        // 3. Interceptarlo y transformarlo a mayúscula antes de que aparezca en el campo
        evt.setKeyChar(Character.toUpperCase(caracter));
    }
    }//GEN-LAST:event_txtNombreKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                PropietarioFormDialog dialog = new PropietarioFormDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblCorreo;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblTelefono;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JTextField txtCorreo;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtTelefono;
    // End of variables declaration//GEN-END:variables
}
